services:
  minio:
    restart: always
    logging: { driver: json-file, options: { max-size: "50m", max-file: "3" } }

  gotenberg:
    restart: always
    logging: { driver: json-file, options: { max-size: "50m", max-file: "3" } }

  postgres:
    restart: always
    logging: { driver: json-file, options: { max-size: "50m", max-file: "3" } }

  search-platform:
    image: ${SEARCH_PLATFORM_IMAGE}
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    logging:
      driver: json-file
      options: { max-size: "50m", max-file: "3" }
